#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_end
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDRestaurante")]
	public partial class BDRestauranteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTUsuario(TUsuario instance);
    partial void UpdateTUsuario(TUsuario instance);
    partial void DeleteTUsuario(TUsuario instance);
    partial void InsertTCategoria(TCategoria instance);
    partial void UpdateTCategoria(TCategoria instance);
    partial void DeleteTCategoria(TCategoria instance);
    partial void InsertTItemPedido(TItemPedido instance);
    partial void UpdateTItemPedido(TItemPedido instance);
    partial void DeleteTItemPedido(TItemPedido instance);
    partial void InsertTPedido(TPedido instance);
    partial void UpdateTPedido(TPedido instance);
    partial void DeleteTPedido(TPedido instance);
    partial void InsertTProducto(TProducto instance);
    partial void UpdateTProducto(TProducto instance);
    partial void DeleteTProducto(TProducto instance);
    partial void InsertTReceta(TReceta instance);
    partial void UpdateTReceta(TReceta instance);
    partial void DeleteTReceta(TReceta instance);
    #endregion
		
		public BDRestauranteDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDRestauranteConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDRestauranteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDRestauranteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDRestauranteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDRestauranteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TUsuario> TUsuario
		{
			get
			{
				return this.GetTable<TUsuario>();
			}
		}
		
		public System.Data.Linq.Table<TCategoria> TCategoria
		{
			get
			{
				return this.GetTable<TCategoria>();
			}
		}
		
		public System.Data.Linq.Table<TDetalleReceta> TDetalleReceta
		{
			get
			{
				return this.GetTable<TDetalleReceta>();
			}
		}
		
		public System.Data.Linq.Table<TItemPedido> TItemPedido
		{
			get
			{
				return this.GetTable<TItemPedido>();
			}
		}
		
		public System.Data.Linq.Table<TPedido> TPedido
		{
			get
			{
				return this.GetTable<TPedido>();
			}
		}
		
		public System.Data.Linq.Table<TProducto> TProducto
		{
			get
			{
				return this.GetTable<TProducto>();
			}
		}
		
		public System.Data.Linq.Table<TReceta> TReceta
		{
			get
			{
				return this.GetTable<TReceta>();
			}
		}
		
		public System.Data.Linq.Table<TBajaProducto> TBajaProducto
		{
			get
			{
				return this.GetTable<TBajaProducto>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarUsuario")]
		public ISingleResult<spEliminarUsuarioResult> spEliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<spEliminarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLogin")]
		public ISingleResult<spLoginResult> spLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, contrasena);
			return ((ISingleResult<spLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearUsuario")]
		public ISingleResult<spCrearUsuarioResult> spCrearUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(100)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(100)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="VarChar(9)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(30)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoUsuario", DbType="VarChar(12)")] string tipoUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellido, direccion, celular, correo, contrasena, tipoUsuario);
			return ((ISingleResult<spCrearUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearCategoria")]
		public ISingleResult<spCrearCategoriaResult> spCrearCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<spCrearCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearProducto")]
		public ISingleResult<spCrearProductoResult> spCrearProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Stock", DbType="Float")] System.Nullable<double> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UnidadMedida", DbType="VarChar(15)")] string unidadMedida, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostoUnitario", DbType="Float")] System.Nullable<double> costoUnitario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ControlProducto", DbType="VarChar(15)")] string controlProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="VarChar(5)")] string idCategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, stock, unidadMedida, costoUnitario, controlProducto, idCategoria);
			return ((ISingleResult<spCrearProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarProducto")]
		public int spEliminarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="VarChar(5)")] string idProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarProducto")]
		public ISingleResult<spEliminarProductoResult> spEliminarProducto1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="VarChar(5)")] string idProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto);
			return ((ISingleResult<spEliminarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearReceta")]
		public ISingleResult<spCrearRecetaResult> spCrearReceta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioVenta", DbType="Float")] System.Nullable<double> precioVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(200)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TiempoCoccion", DbType="Int")] System.Nullable<int> tiempoCoccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoReceta", DbType="VarChar(15)")] string tipoReceta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, precioVenta, descripcion, tiempoCoccion, tipoReceta);
			return ((ISingleResult<spCrearRecetaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearDetalleReceta")]
		public int spCrearDetalleReceta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReceta", DbType="VarChar(5)")] string idReceta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostoEnReceta", DbType="Float")] System.Nullable<double> costoEnReceta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRecetaProducto", DbType="VarChar(5)")] string idRecetaProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Selector", DbType="VarChar(1)")] string selector, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantidadProducto", DbType="Float")] System.Nullable<double> cantidadProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReceta, costoEnReceta, idRecetaProducto, selector, cantidadProducto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearDetalleReceta")]
		public ISingleResult<spCrearDetalleRecetaResult> spCrearDetalleReceta1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReceta", DbType="VarChar(5)")] string idReceta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostoEnReceta", DbType="Float")] System.Nullable<double> costoEnReceta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRecetaProducto", DbType="VarChar(5)")] string idRecetaProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Selector", DbType="VarChar(1)")] string selector, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantidadProducto", DbType="Float")] System.Nullable<double> cantidadProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReceta, costoEnReceta, idRecetaProducto, selector, cantidadProducto);
			return ((ISingleResult<spCrearDetalleRecetaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearBajaProducto")]
		public ISingleResult<spCrearBajaProductoResult> spCrearBajaProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="VarChar(5)")] string idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Float")] System.Nullable<double> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Motivo", DbType="VarChar(250)")] string motivo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, cantidad, motivo);
			return ((ISingleResult<spCrearBajaProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spRegistrarStock")]
		public int spRegistrarStock([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="VarChar(5)")] string idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Float")] System.Nullable<double> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, cantidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spRegistrarStock")]
		public ISingleResult<spRegistrarStockResult> spRegistrarStock1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="VarChar(5)")] string idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Float")] System.Nullable<double> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, cantidad);
			return ((ISingleResult<spRegistrarStockResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearItemPedido")]
		public ISingleResult<spCrearItemPedidoResult> spCrearItemPedido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioPedido", DbType="Float")] System.Nullable<double> precioPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPedido", DbType="VarChar(5)")] string idPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReceta", DbType="VarChar(5)")] string idReceta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), precioPedido, cantidad, idPedido, idReceta);
			return ((ISingleResult<spCrearItemPedidoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearPedido")]
		public ISingleResult<spCrearPedidoResult> spCrearPedido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalVenta", DbType="Float")] System.Nullable<double> totalVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(30)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), totalVenta, username);
			return ((ISingleResult<spCrearPedidoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearItemPedido")]
		public ISingleResult<spCrearItemPedidoResult1> spCrearItemPedido1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioPedido", DbType="Float")] System.Nullable<double> precioPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPedido", DbType="VarChar(5)")] string idPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReceta", DbType="VarChar(5)")] string idReceta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), precioPedido, cantidad, idPedido, idReceta);
			return ((ISingleResult<spCrearItemPedidoResult1>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUsuario")]
	public partial class TUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdUsuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private string _Celular;
		
		private string _Correo;
		
		private string _Contrasena;
		
		private string _TipoUsuario;
		
		private string _Estado;
		
		private EntitySet<TPedido> _TPedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(string value);
    partial void OnIdUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnTipoUsuarioChanging(string value);
    partial void OnTipoUsuarioChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public TUsuario()
		{
			this._TPedido = new EntitySet<TPedido>(new Action<TPedido>(this.attach_TPedido), new Action<TPedido>(this.detach_TPedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(9)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUsuario", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TipoUsuario
		{
			get
			{
				return this._TipoUsuario;
			}
			set
			{
				if ((this._TipoUsuario != value))
				{
					this.OnTipoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._TipoUsuario = value;
					this.SendPropertyChanged("TipoUsuario");
					this.OnTipoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TPedido", Storage="_TPedido", ThisKey="IdUsuario", OtherKey="IdUsuario")]
		public EntitySet<TPedido> TPedido
		{
			get
			{
				return this._TPedido;
			}
			set
			{
				this._TPedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TPedido(TPedido entity)
		{
			this.SendPropertyChanging();
			entity.TUsuario = this;
		}
		
		private void detach_TPedido(TPedido entity)
		{
			this.SendPropertyChanging();
			entity.TUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TCategoria")]
	public partial class TCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdCategoria;
		
		private string _Nombre;
		
		private EntitySet<TProducto> _TProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCategoriaChanging(string value);
    partial void OnIdCategoriaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public TCategoria()
		{
			this._TProducto = new EntitySet<TProducto>(new Action<TProducto>(this.attach_TProducto), new Action<TProducto>(this.detach_TProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this.OnIdCategoriaChanging(value);
					this.SendPropertyChanging();
					this._IdCategoria = value;
					this.SendPropertyChanged("IdCategoria");
					this.OnIdCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCategoria_TProducto", Storage="_TProducto", ThisKey="IdCategoria", OtherKey="IdCategoria")]
		public EntitySet<TProducto> TProducto
		{
			get
			{
				return this._TProducto;
			}
			set
			{
				this._TProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TProducto(TProducto entity)
		{
			this.SendPropertyChanging();
			entity.TCategoria = this;
		}
		
		private void detach_TProducto(TProducto entity)
		{
			this.SendPropertyChanging();
			entity.TCategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TDetalleReceta")]
	public partial class TDetalleReceta
	{
		
		private double _CantidadProducto;
		
		private double _CostoEnReceta;
		
		private string _IdProducto;
		
		private string _IdReceta;
		
		public TDetalleReceta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadProducto", DbType="Float NOT NULL")]
		public double CantidadProducto
		{
			get
			{
				return this._CantidadProducto;
			}
			set
			{
				if ((this._CantidadProducto != value))
				{
					this._CantidadProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoEnReceta", DbType="Float NOT NULL")]
		public double CostoEnReceta
		{
			get
			{
				return this._CostoEnReceta;
			}
			set
			{
				if ((this._CostoEnReceta != value))
				{
					this._CostoEnReceta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReceta", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdReceta
		{
			get
			{
				return this._IdReceta;
			}
			set
			{
				if ((this._IdReceta != value))
				{
					this._IdReceta = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TItemPedido")]
	public partial class TItemPedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _PrecioUnitario;
		
		private int _cantidad;
		
		private string _IdPedido;
		
		private string _IdReceta;
		
		private EntityRef<TPedido> _TPedido;
		
		private EntityRef<TReceta> _TReceta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrecioUnitarioChanging(double value);
    partial void OnPrecioUnitarioChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnIdPedidoChanging(string value);
    partial void OnIdPedidoChanged();
    partial void OnIdRecetaChanging(string value);
    partial void OnIdRecetaChanged();
    #endregion
		
		public TItemPedido()
		{
			this._TPedido = default(EntityRef<TPedido>);
			this._TReceta = default(EntityRef<TReceta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioUnitario", DbType="Float NOT NULL")]
		public double PrecioUnitario
		{
			get
			{
				return this._PrecioUnitario;
			}
			set
			{
				if ((this._PrecioUnitario != value))
				{
					this.OnPrecioUnitarioChanging(value);
					this.SendPropertyChanging();
					this._PrecioUnitario = value;
					this.SendPropertyChanged("PrecioUnitario");
					this.OnPrecioUnitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPedido", DbType="VarChar(5)")]
		public string IdPedido
		{
			get
			{
				return this._IdPedido;
			}
			set
			{
				if ((this._IdPedido != value))
				{
					if (this._TPedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPedidoChanging(value);
					this.SendPropertyChanging();
					this._IdPedido = value;
					this.SendPropertyChanged("IdPedido");
					this.OnIdPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReceta", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdReceta
		{
			get
			{
				return this._IdReceta;
			}
			set
			{
				if ((this._IdReceta != value))
				{
					if (this._TReceta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdRecetaChanging(value);
					this.SendPropertyChanging();
					this._IdReceta = value;
					this.SendPropertyChanged("IdReceta");
					this.OnIdRecetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TPedido_TItemPedido", Storage="_TPedido", ThisKey="IdPedido", OtherKey="IdPedido", IsForeignKey=true)]
		public TPedido TPedido
		{
			get
			{
				return this._TPedido.Entity;
			}
			set
			{
				TPedido previousValue = this._TPedido.Entity;
				if (((previousValue != value) 
							|| (this._TPedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TPedido.Entity = null;
						previousValue.TItemPedido.Remove(this);
					}
					this._TPedido.Entity = value;
					if ((value != null))
					{
						value.TItemPedido.Add(this);
						this._IdPedido = value.IdPedido;
					}
					else
					{
						this._IdPedido = default(string);
					}
					this.SendPropertyChanged("TPedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TReceta_TItemPedido", Storage="_TReceta", ThisKey="IdReceta", OtherKey="IdReceta", IsForeignKey=true)]
		public TReceta TReceta
		{
			get
			{
				return this._TReceta.Entity;
			}
			set
			{
				TReceta previousValue = this._TReceta.Entity;
				if (((previousValue != value) 
							|| (this._TReceta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TReceta.Entity = null;
						previousValue.TItemPedido = null;
					}
					this._TReceta.Entity = value;
					if ((value != null))
					{
						value.TItemPedido = this;
						this._IdReceta = value.IdReceta;
					}
					else
					{
						this._IdReceta = default(string);
					}
					this.SendPropertyChanged("TReceta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TPedido")]
	public partial class TPedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdPedido;
		
		private double _TotalVenta;
		
		private System.DateTime _FechaVenta;
		
		private string _EstadoPedido;
		
		private string _IdUsuario;
		
		private EntitySet<TItemPedido> _TItemPedido;
		
		private EntityRef<TUsuario> _TUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPedidoChanging(string value);
    partial void OnIdPedidoChanged();
    partial void OnTotalVentaChanging(double value);
    partial void OnTotalVentaChanged();
    partial void OnFechaVentaChanging(System.DateTime value);
    partial void OnFechaVentaChanged();
    partial void OnEstadoPedidoChanging(string value);
    partial void OnEstadoPedidoChanged();
    partial void OnIdUsuarioChanging(string value);
    partial void OnIdUsuarioChanged();
    #endregion
		
		public TPedido()
		{
			this._TItemPedido = new EntitySet<TItemPedido>(new Action<TItemPedido>(this.attach_TItemPedido), new Action<TItemPedido>(this.detach_TItemPedido));
			this._TUsuario = default(EntityRef<TUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPedido", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdPedido
		{
			get
			{
				return this._IdPedido;
			}
			set
			{
				if ((this._IdPedido != value))
				{
					this.OnIdPedidoChanging(value);
					this.SendPropertyChanging();
					this._IdPedido = value;
					this.SendPropertyChanged("IdPedido");
					this.OnIdPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalVenta", DbType="Float NOT NULL")]
		public double TotalVenta
		{
			get
			{
				return this._TotalVenta;
			}
			set
			{
				if ((this._TotalVenta != value))
				{
					this.OnTotalVentaChanging(value);
					this.SendPropertyChanging();
					this._TotalVenta = value;
					this.SendPropertyChanged("TotalVenta");
					this.OnTotalVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVenta", DbType="Date NOT NULL")]
		public System.DateTime FechaVenta
		{
			get
			{
				return this._FechaVenta;
			}
			set
			{
				if ((this._FechaVenta != value))
				{
					this.OnFechaVentaChanging(value);
					this.SendPropertyChanging();
					this._FechaVenta = value;
					this.SendPropertyChanged("FechaVenta");
					this.OnFechaVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoPedido", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string EstadoPedido
		{
			get
			{
				return this._EstadoPedido;
			}
			set
			{
				if ((this._EstadoPedido != value))
				{
					this.OnEstadoPedidoChanging(value);
					this.SendPropertyChanging();
					this._EstadoPedido = value;
					this.SendPropertyChanged("EstadoPedido");
					this.OnEstadoPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._TUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TPedido_TItemPedido", Storage="_TItemPedido", ThisKey="IdPedido", OtherKey="IdPedido")]
		public EntitySet<TItemPedido> TItemPedido
		{
			get
			{
				return this._TItemPedido;
			}
			set
			{
				this._TItemPedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TPedido", Storage="_TUsuario", ThisKey="IdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public TUsuario TUsuario
		{
			get
			{
				return this._TUsuario.Entity;
			}
			set
			{
				TUsuario previousValue = this._TUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TUsuario.Entity = null;
						previousValue.TPedido.Remove(this);
					}
					this._TUsuario.Entity = value;
					if ((value != null))
					{
						value.TPedido.Add(this);
						this._IdUsuario = value.IdUsuario;
					}
					else
					{
						this._IdUsuario = default(string);
					}
					this.SendPropertyChanged("TUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TItemPedido(TItemPedido entity)
		{
			this.SendPropertyChanging();
			entity.TPedido = this;
		}
		
		private void detach_TItemPedido(TItemPedido entity)
		{
			this.SendPropertyChanging();
			entity.TPedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TProducto")]
	public partial class TProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdProducto;
		
		private string _Nombre;
		
		private double _Stock;
		
		private string _UnidadMedida;
		
		private double _CostoUnitario;
		
		private System.DateTime _FechaRegistro;
		
		private string _EstadoProducto;
		
		private string _ControlProducto;
		
		private string _IdCategoria;
		
		private EntityRef<TCategoria> _TCategoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdProductoChanging(string value);
    partial void OnIdProductoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnStockChanging(double value);
    partial void OnStockChanged();
    partial void OnUnidadMedidaChanging(string value);
    partial void OnUnidadMedidaChanged();
    partial void OnCostoUnitarioChanging(double value);
    partial void OnCostoUnitarioChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnEstadoProductoChanging(string value);
    partial void OnEstadoProductoChanged();
    partial void OnControlProductoChanging(string value);
    partial void OnControlProductoChanged();
    partial void OnIdCategoriaChanging(string value);
    partial void OnIdCategoriaChanged();
    #endregion
		
		public TProducto()
		{
			this._TCategoria = default(EntityRef<TCategoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this.OnIdProductoChanging(value);
					this.SendPropertyChanging();
					this._IdProducto = value;
					this.SendPropertyChanged("IdProducto");
					this.OnIdProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Float NOT NULL")]
		public double Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this.OnStockChanging(value);
					this.SendPropertyChanging();
					this._Stock = value;
					this.SendPropertyChanged("Stock");
					this.OnStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadMedida", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string UnidadMedida
		{
			get
			{
				return this._UnidadMedida;
			}
			set
			{
				if ((this._UnidadMedida != value))
				{
					this.OnUnidadMedidaChanging(value);
					this.SendPropertyChanging();
					this._UnidadMedida = value;
					this.SendPropertyChanged("UnidadMedida");
					this.OnUnidadMedidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoUnitario", DbType="Float NOT NULL")]
		public double CostoUnitario
		{
			get
			{
				return this._CostoUnitario;
			}
			set
			{
				if ((this._CostoUnitario != value))
				{
					this.OnCostoUnitarioChanging(value);
					this.SendPropertyChanging();
					this._CostoUnitario = value;
					this.SendPropertyChanged("CostoUnitario");
					this.OnCostoUnitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="Date NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoProducto", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string EstadoProducto
		{
			get
			{
				return this._EstadoProducto;
			}
			set
			{
				if ((this._EstadoProducto != value))
				{
					this.OnEstadoProductoChanging(value);
					this.SendPropertyChanging();
					this._EstadoProducto = value;
					this.SendPropertyChanged("EstadoProducto");
					this.OnEstadoProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ControlProducto", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ControlProducto
		{
			get
			{
				return this._ControlProducto;
			}
			set
			{
				if ((this._ControlProducto != value))
				{
					this.OnControlProductoChanging(value);
					this.SendPropertyChanging();
					this._ControlProducto = value;
					this.SendPropertyChanged("ControlProducto");
					this.OnControlProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					if (this._TCategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCategoriaChanging(value);
					this.SendPropertyChanging();
					this._IdCategoria = value;
					this.SendPropertyChanged("IdCategoria");
					this.OnIdCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCategoria_TProducto", Storage="_TCategoria", ThisKey="IdCategoria", OtherKey="IdCategoria", IsForeignKey=true)]
		public TCategoria TCategoria
		{
			get
			{
				return this._TCategoria.Entity;
			}
			set
			{
				TCategoria previousValue = this._TCategoria.Entity;
				if (((previousValue != value) 
							|| (this._TCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TCategoria.Entity = null;
						previousValue.TProducto.Remove(this);
					}
					this._TCategoria.Entity = value;
					if ((value != null))
					{
						value.TProducto.Add(this);
						this._IdCategoria = value.IdCategoria;
					}
					else
					{
						this._IdCategoria = default(string);
					}
					this.SendPropertyChanged("TCategoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TReceta")]
	public partial class TReceta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdReceta;
		
		private string _Nombre;
		
		private double _CostoReceta;
		
		private double _PrecioVenta;
		
		private string _Descripcion;
		
		private int _TiempoCoccion;
		
		private string _TipoReceta;
		
		private string _EstadoReceta;
		
		private EntityRef<TItemPedido> _TItemPedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRecetaChanging(string value);
    partial void OnIdRecetaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCostoRecetaChanging(double value);
    partial void OnCostoRecetaChanged();
    partial void OnPrecioVentaChanging(double value);
    partial void OnPrecioVentaChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnTiempoCoccionChanging(int value);
    partial void OnTiempoCoccionChanged();
    partial void OnTipoRecetaChanging(string value);
    partial void OnTipoRecetaChanged();
    partial void OnEstadoRecetaChanging(string value);
    partial void OnEstadoRecetaChanged();
    #endregion
		
		public TReceta()
		{
			this._TItemPedido = default(EntityRef<TItemPedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReceta", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdReceta
		{
			get
			{
				return this._IdReceta;
			}
			set
			{
				if ((this._IdReceta != value))
				{
					this.OnIdRecetaChanging(value);
					this.SendPropertyChanging();
					this._IdReceta = value;
					this.SendPropertyChanged("IdReceta");
					this.OnIdRecetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoReceta", DbType="Float NOT NULL")]
		public double CostoReceta
		{
			get
			{
				return this._CostoReceta;
			}
			set
			{
				if ((this._CostoReceta != value))
				{
					this.OnCostoRecetaChanging(value);
					this.SendPropertyChanging();
					this._CostoReceta = value;
					this.SendPropertyChanged("CostoReceta");
					this.OnCostoRecetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVenta", DbType="Float NOT NULL")]
		public double PrecioVenta
		{
			get
			{
				return this._PrecioVenta;
			}
			set
			{
				if ((this._PrecioVenta != value))
				{
					this.OnPrecioVentaChanging(value);
					this.SendPropertyChanging();
					this._PrecioVenta = value;
					this.SendPropertyChanged("PrecioVenta");
					this.OnPrecioVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TiempoCoccion", DbType="Int NOT NULL")]
		public int TiempoCoccion
		{
			get
			{
				return this._TiempoCoccion;
			}
			set
			{
				if ((this._TiempoCoccion != value))
				{
					this.OnTiempoCoccionChanging(value);
					this.SendPropertyChanging();
					this._TiempoCoccion = value;
					this.SendPropertyChanged("TiempoCoccion");
					this.OnTiempoCoccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoReceta", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TipoReceta
		{
			get
			{
				return this._TipoReceta;
			}
			set
			{
				if ((this._TipoReceta != value))
				{
					this.OnTipoRecetaChanging(value);
					this.SendPropertyChanging();
					this._TipoReceta = value;
					this.SendPropertyChanged("TipoReceta");
					this.OnTipoRecetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoReceta", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string EstadoReceta
		{
			get
			{
				return this._EstadoReceta;
			}
			set
			{
				if ((this._EstadoReceta != value))
				{
					this.OnEstadoRecetaChanging(value);
					this.SendPropertyChanging();
					this._EstadoReceta = value;
					this.SendPropertyChanged("EstadoReceta");
					this.OnEstadoRecetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TReceta_TItemPedido", Storage="_TItemPedido", ThisKey="IdReceta", OtherKey="IdReceta", IsUnique=true, IsForeignKey=false)]
		public TItemPedido TItemPedido
		{
			get
			{
				return this._TItemPedido.Entity;
			}
			set
			{
				TItemPedido previousValue = this._TItemPedido.Entity;
				if (((previousValue != value) 
							|| (this._TItemPedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TItemPedido.Entity = null;
						previousValue.TReceta = null;
					}
					this._TItemPedido.Entity = value;
					if ((value != null))
					{
						value.TReceta = this;
					}
					this.SendPropertyChanged("TItemPedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBajaProducto")]
	public partial class TBajaProducto
	{
		
		private string _IdProducto;
		
		private double _Cantidad;
		
		private string _Motivo;
		
		private System.DateTime _Fecha;
		
		public TBajaProducto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Float NOT NULL")]
		public double Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motivo", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Motivo
		{
			get
			{
				return this._Motivo;
			}
			set
			{
				if ((this._Motivo != value))
				{
					this._Motivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class spEliminarUsuarioResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spEliminarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spLoginResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spCrearUsuarioResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCrearUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(27) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spCrearCategoriaResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCrearCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spCrearProductoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCrearProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(37) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spEliminarProductoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spEliminarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spCrearRecetaResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCrearRecetaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spCrearDetalleRecetaResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCrearDetalleRecetaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spCrearBajaProductoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCrearBajaProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(47) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spRegistrarStockResult
	{
		
		private int _CodError;
		
		public spRegistrarStockResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
	}
	
	public partial class spCrearItemPedidoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCrearItemPedidoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(29) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spCrearPedidoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCrearPedidoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="Char(5)")]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spCrearItemPedidoResult1
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCrearItemPedidoResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(29) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
